#
# Blog Settings
#
name: Jeferson DEV
title: Developer blog with some useful info about .NET and Force.com
author: Jéferson Chaves
url: http://jefersonchaves.github.io

#
# Github repositories
#
github_user: jefersonchaves
github_repo_url: https://github.com/jefersonspencer/jefersonchaves.github.io/

#
# Disqus comments
#
disqus_short_name: jefersondev
disqus_show_comment_count: true

#
# Jekyll Settings
#
permalink: /archive/:year/:month/:day/:title/
highlighter: rouge

gems:
  - jekyll-sitemap
